import { Box, Flex, Text } from '@chakra-ui/react'
import Head from 'next/head'
import { Header, Main, Footer } from '../components/layout'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>

      <Main>
        <Box w={'full'} >
          <Box h='20rem' bg='blue.800'>
            <Text>Hello word</Text>
          </Box>
          <Box h='20rem' bg='blue.800'>
            <Text>Hello word</Text>
          </Box>
          <Box h='20rem' bg='blue.800'>
            <Text>Hello word</Text>
          </Box>
          <Box h='20rem' bg='blue.800'>
            <Text>Hello word</Text>
          </Box>
          <Box h='20rem' bg='blue.800'>
            <Text>Hello word</Text>
          </Box>
          <Box h='20rem' bg='blue.800'>
            <Text>Hello word</Text>
          </Box>
          <Box h='20rem' bg='blue.800'>
            <Text>Hello word</Text>
          </Box>
        </Box>
      </Main>

      <Footer/>
    </div>
  )
}
