import { Box, Flex, Text } from '@chakra-ui/react'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import { Header, Main, Footer } from '../components/layout'
import { useUserV2 } from '../hooks/useUser'
import Axios from 'axios'

export default function Home() {
  const {data, countol, clikData} =useUserV2()
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* {countol}
      <button onClick={clikData}>+</button>

      {data.map(e=>{
        return(
          <div key={e.id}>
            <p>{e.name}</p>
          </div>
        )
      })} */}

      <Header/>

      <Main>
        <Box w={'full'} >
          <Box h='20rem' bg='blue.800'>
            <Text>Hello word</Text>
          </Box>
        </Box>
      </Main>

      <Footer/>
    </div>
  )
}
